#ifndef AUTOTUNE_PARAMS_H
#define AUTOTUNE_PARAMS_H

#define SIGNAL_BUFF_LEN 1024

#define ADC_BUFF_LEN 2 * SIGNAL_BUFF_LEN
#define ADC_SAMPLE_RATE 8000

#define MPM_LAG_STOP_SEARCH 150
#define MPM_BUFF_SIZE MPM_LAG_STOP_SEARCH
#define MPM_CLARITY_RATIO 0.9f
#define MPM_PEAK_THRESHOLD 0.8f
#define MPM_MAX_NUM_PEAKS 15

#define DSP_KON 10.0f
#define DSP_KOFF 5.0f

#endif /* AUTOTUNE_PARAMS_H */